---
name: 'Install pre-commit'

description: 'Installs pre-commit and related packages'

inputs:
  operating-systems:
    description: "Defaults to ['ubuntu-latest'] if not set."
    default: "ubuntu-latest"
  node-version:
    description: "Optional input to set the version of Node.js used to build the project."
    default: '22.x'
  node-caching:
    description: "Optional input to set up caching for the setup-node action. The input syntax corresponds to the setup-node's one."
    default: 'pnpm'

runs:
  using: "composite"
  steps:
    - name: checkout
      uses: actions/checkout@v4

    - name: install pnpm
      uses: pnpm/action-setup@v4
      with:
        run_install: false

    - name: setup node.js ${{ inputs.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ inputs.node-version }}
        cache: ${{ inputs.node-caching }}

    - name: install dependencies
      run: pnpm install
      shell: bash

    - name: run linter
      run: pnpm run lint
      shell: bash

    - name: run commit linter
      run: pnpm prepare
      shell: bash
