name: Basic validation

on:
  workflow_call:
    inputs:
      operating-systems:
        description: "Defaults to ['ubuntu-latest'] if not set"
        required: false
        type: string
        default: "ubuntu-latest"
      enable-audit:
        description: 'Optional input to enable pnpm package audit process'
        required: false
        type: boolean
        default: true
      node-version:
        description: "Optional input to set the version of Node.js used to build the project."
        required: false
        type: string
        default: '22.x'
      node-caching:
        description: "Optional input to set up caching for the setup-node action. The input syntax corresponds to the setup-node's one."
        required: false
        type: string
        default: 'pnpm'

jobs:
  build:
    runs-on: ${{ inputs.operating-systems }}
    
    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: install pnpm
        uses: pnpm/action-setup@v4
        with:
          node-version: 10
          run_install: false

      - name: setup node.js ${{ inputs.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ inputs.node-version }}
          cache: ${{ inputs.node-caching }}

      - name: install dependencies
        run: pnpm install

      - name: run linter
        run: pnpm run lint

      - name: run commit linter
        run: pnpm prepare

      - name: test
        run: pnpm vitest --coverage.enabled true

      - name: build
        run: pnpm run build

      - name: audit packages
        run: pnpm audit --audit-level=high
        if: ${{ inputs.enable-audit }}
