name: unit testing code coverage

on:
  workflow_call:
    inputs:
      operating-systems:
        description: "Optional input to set a list of operating systems which the workflow uses."
        required: false
        type: string
        default: "['ubuntu-latest']"
      node-version:
        description: "Optional input to set the version of Node.js used to build the project."
        required: false
        type: string
        default: '22.x'
      node-caching:
        description: "Optional input to set up caching for the setup-node action."
        required: false
        type: string
        default: 'pnpm'

jobs:
  skins-build:
    runs-on: ${{ fromJSON(inputs.operating-systems)[0] }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          run_install: false

      - name: Install node.js ${{ inputs.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ inputs.node-version }}
          cache: ${{ inputs.node-caching }}

      - name: Install dependencies
        run: pnpm install

      - name: Run commit linter
        run: pnpm prepare

      - name: Run linter
        run: pnpm run lint        

      - name: Run build skins
        run: pnpm build:skins

      - name: Package into artifact
        run: |
          cd dist
          pnpm pack

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: skins
          path: ./dist/qbit.design-skins-*.tgz

  shell-build:
    runs-on: ${{ fromJSON(inputs.operating-systems)[0] }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          run_install: false

      - name: Install Node.js ${{ inputs.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ inputs.node-version }}
          cache: ${{ inputs.node-caching }}

      - name: Install dependencies
        run: pnpm install

      - name: Rub build components
        run: pnpm build:components

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: shell
          path: ./dist