name: unit testing code coverage

on:
  workflow_call:
    inputs:
      operating-systems:
        description: "Optional input to set a list of operating systems which the workflow uses."
        required: false
        type: string
        default: "['ubuntu-latest']"
      node-version:
        description: "Optional input to set the version of Node.js used to build the project."
        required: false
        type: string
        default: '22.x'
      node-caching:
        description: "Optional input to set up caching for the setup-node action."
        required: false
        type: string
        default: 'pnpm'

jobs:
  build-pages:
    runs-on: ${{ fromJSON(inputs.operating-systems)[0] }}
    steps:
      - name: Run pre build script
        uses: alphacode-kirushnarajg/alpha-gitflow/.github/actions/install-pre-commit@main

      - name: Build storybook
        run: pnpm build:storybook

      - name: Upload build artifact
        id: storybook
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./dist/storybook
