name: unit testing code coverage

on:
  workflow_call:
    inputs:
      operating-systems:
        description: "Optional input to set a list of operating systems which the workflow uses."
        required: false
        type: string
        default: "['ubuntu-latest']"
      node-version:
        description: "Optional input to set the version of Node.js used to build the project."
        required: false
        type: string
        default: '22.x'
      node-caching:
        description: "Optional input to set up caching for the setup-node action."
        required: false
        type: string
        default: 'pnpm'

jobs:
  publish:
    runs-on: ${{ fromJSON(inputs.operating-systems)[0] }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          node-version: 10
          run_install: false

      - name: Install node.js ${{ inputs.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ inputs.node-version }}
          cache: ${{ inputs.node-caching }}
          registry-url: https://registry.npmjs.org

      - name: Install dependencies
        run: pnpm install

      - name: Build skins
        run: pnpm build:skins

      - name: Publish to NPM registry
        shell: bash
        run: pnpm publish ./dist --access public --no-git-checks
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NODE_AUTH_TOKEN }}

      - name: Package into artifact
        run: pnpm pack --pack-destination ./dist

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: skins
          path: ./dist/qbit.design-skins-*.tgz          
