name: unit testing code coverage

on:
  workflow_call:
    inputs:
      operating-systems:
        description: "Optional input to set a list of operating systems which the workflow uses."
        required: false
        type: string
        default: "['ubuntu-latest']"
      node-version:
        description: "Optional input to set the version of Node.js used to build the project."
        required: false
        type: string
        default: '22.x'
      node-caching:
        description: "Optional input to set up caching for the setup-node action."
        required: false
        type: string
        default: 'pnpm'

jobs:
  publish:
    runs-on: ${{ fromJSON(inputs.operating-systems)[0] }}
    steps:
      - name: Run pre build script
        uses: alphacode-kirushnarajg/alpha-gitflow/.github/actions/install-pre-commit@main

      - name: Build skins
        run: pnpm build:skins

      - name: Publish to NPM registry
        shell: bash
        run: pnpm publish ./dist --access public --no-git-checks
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NODE_AUTH_TOKEN }}

      - name: Package into artifact
        run: pnpm pack --pack-destination ./dist

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: skins
          path: ./dist/qbit.design-skins-*.tgz          
