name: unit testing coverage report

on:
  workflow_call:
    inputs:
      operating-systems:
        description: "Optional input to set a list of operating systems which the workflow uses."
        required: false
        type: string
        default: "['ubuntu-latest']"

jobs:
  coverage-report:
    runs-on: ${{ fromJSON(inputs.operating-systems)[0] }}
    steps:
      - name: Download coverage artifacts
        uses: actions/download-artifact@v4
        with:
          name: coverage
          path: ./coverage

      - name: Report coverage
        uses: davelosert/vitest-coverage-report-action@v2
        with:
          json-summary-compare-path: ./coverage/coverage-summary.json
