name: unit testing

on:
  workflow_call:
    workflows: ["unit testing"]
    types:
      - completed
    inputs:
      operating-systems:
        description: "Optional input to set a list of operating systems which the workflow uses."
        required: false
        type: string
        default: "['ubuntu-latest']"

jobs:
  test:
    runs-on: ${{ matrix.operating-systems }}
    strategy:
      fail-fast: false
      matrix:
        operating-systems: ${{ inputs.operating-systems }}

  report:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: "Download Coverage Artifacts"
        uses: actions/download-artifact@v4
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          run-id: ${{ github.event.workflow_run.id }}
          name: coverage
          path: ./.testing

      - name: "Report Coverage"
        uses: davelosert/vitest-coverage-report-action@v2
        with:
          json-summary-compare-path: coverage-main/coverage-summary.json
          